-- =====================================================================
-- Skema basis data purwarupa Analitik CCTV Lalu Lintas - Dishub DKI Jakarta
-- Dialek: PostgreSQL 14+
--
-- Basis data yang BERJALAN saat ini adalah SQLite (runs/lalin.db). Berkas ini
-- padanan PostgreSQL-nya, untuk tim DB dan untuk migrasi produksi. Struktur,
-- nama kolom, dan batasan sama; perbedaannya hanya dialek:
--   SQLite INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY (BY DEFAULT: ID lama ikut dipindah apa adanya, karena foto bukti runs/_bukti/<id>.jpg merujuknya)
--   SQLite TEXT berisi ISO-8601 UTC         -> TIMESTAMPTZ
--   SQLite TEXT berisi JSON                 -> JSONB
--   SQLite INTEGER 0/1                      -> BOOLEAN
-- Sumber kebenaran skema SQLite: src/lalin/store.py (SCHEMA, MIGRASI_EVENTS)
-- dan src/lalin/sql/aduan.sql.
--
-- DATA PRIBADI: tidak ada kolom identitas pelapor maupun pengendara. Pelat
-- nomor tidak disimpan di basis data ini. Aduan hanya menyimpan nomor tiket
-- sistem asal (UU No. 27/2022 tentang Pelindungan Data Pribadi).
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS lalin;
SET search_path TO lalin;

-- ---------------------------------------------------------------------
-- Satu siklus analisis = satu klip pendek dari satu kamera.
-- Tabel ini juga bukti CAKUPAN: kamera hanya dipantau pada saat-saat
-- tercatat di sini, bukan 24 jam penuh.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cycles (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    camera        TEXT        NOT NULL,          -- key di configs/cameras.yml
    scenario      TEXT,
    started_at    TIMESTAMPTZ NOT NULL,
    finished_at   TIMESTAMPTZ NOT NULL,
    ok            BOOLEAN     NOT NULL,
    frames        INTEGER     NOT NULL DEFAULT 0,
    unique_tracks INTEGER     NOT NULL DEFAULT 0,
    elapsed_sec   REAL        NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_cycles_finished ON cycles (finished_at);
CREATE INDEX IF NOT EXISTS idx_cycles_camera   ON cycles (camera, finished_at);

-- ---------------------------------------------------------------------
-- Kejadian (temuan pelanggaran) hasil deteksi, beserta keputusan petugas.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cycle_id      BIGINT      REFERENCES cycles (id),
    camera        TEXT        NOT NULL,
    kind          TEXT        NOT NULL
                  CHECK (kind IN ('parkir_liar', 'ngetem', 'jalur_sepeda', 'angkutan_barang',
                                  'busway', 'lawan_arah', 'langgar_marka')),
    -- 'dishub' = kewenangan administratif Dishub; 'rujuk' = pelanggaran lalu
    -- lintas bergerak, kewenangan Polri (dirujuk, bukan ditindak Dishub).
    authority     TEXT        NOT NULL CHECK (authority IN ('dishub', 'rujuk')),
    track_id      INTEGER,
    first_sec     REAL,                           -- detik ke-berapa dalam klip
    duration_sec  REAL,
    threshold_sec INTEGER,                        -- ambang parkir yang berlaku
    detected_at   TIMESTAMPTZ NOT NULL,           -- = cycles.finished_at
    verified      BOOLEAN     NOT NULL DEFAULT FALSE,
    verdict       TEXT        CHECK (verdict IS NULL OR verdict IN ('benar', 'bukan')),
    verified_at   TIMESTAMPTZ,
    verified_by   TEXT,
    verify_note   TEXT
);
CREATE INDEX IF NOT EXISTS idx_events_detected ON events (detected_at);
CREATE INDEX IF NOT EXISTS idx_events_camera   ON events (camera, detected_at);
-- Foto bukti tiap kejadian ada di berkas runs/_bukti/<id>.jpg (bukan BLOB),
-- dilayani lewat GET /api/events/<id>/bukti.

-- ---------------------------------------------------------------------
-- Aduan masyarakat
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS aduan (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sumber          TEXT        NOT NULL DEFAULT 'crm'
                    CHECK (sumber IN ('crm', 'jaki', 'telepon', 'medsos', 'petugas')),
    ref_sumber      TEXT,                          -- nomor tiket di sistem asal
    kategori        TEXT        NOT NULL
                    CHECK (kategori IN ('parkir_liar', 'lawan_arah', 'langgar_marka',
                                        'jalur_sepeda', 'ngetem', 'kemacetan', 'lainnya')),
    deskripsi       TEXT,
    lokasi_teks     TEXT        NOT NULL,
    wilayah         TEXT,
    lat             DOUBLE PRECISION CHECK (lat IS NULL OR lat BETWEEN -90 AND 90),
    lon             DOUBLE PRECISION CHECK (lon IS NULL OR lon BETWEEN -180 AND 180),
    kamera_dugaan   TEXT,
    waktu_kejadian  TIMESTAMPTZ NOT NULL,
    waktu_lapor     TIMESTAMPTZ NOT NULL,
    status          TEXT        NOT NULL DEFAULT 'baru'
                    CHECK (status IN ('baru', 'ada_kandidat', 'terbukti', 'tidak_ditemukan',
                                      'tidak_terpantau', 'di_luar_cakupan', 'selesai')),
    cakupan         JSONB,                         -- kamera diperiksa, siklus terekam, rentang
    catatan         TEXT,
    dibuat          TIMESTAMPTZ NOT NULL DEFAULT now(),
    diubah          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_aduan_tiket UNIQUE (sumber, ref_sumber),
    CONSTRAINT ck_aduan_koordinat CHECK ((lat IS NULL) = (lon IS NULL))
);
CREATE INDEX IF NOT EXISTS idx_aduan_waktu  ON aduan (waktu_kejadian);
CREATE INDEX IF NOT EXISTS idx_aduan_status ON aduan (status);

CREATE TABLE IF NOT EXISTS aduan_kecocokan (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aduan_id        BIGINT      NOT NULL REFERENCES aduan (id) ON DELETE CASCADE,
    event_id        BIGINT      NOT NULL REFERENCES events (id),
    skor            REAL        NOT NULL CHECK (skor BETWEEN 0 AND 1),
    alasan          JSONB       NOT NULL,          -- rincian komponen skor
    keputusan       TEXT        NOT NULL DEFAULT 'kandidat'
                    CHECK (keputusan IN ('kandidat', 'dikonfirmasi', 'ditolak')),
    diputus_pada    TIMESTAMPTZ,
    catatan         TEXT,
    dibuat          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_kecocokan UNIQUE (aduan_id, event_id)
);
CREATE INDEX IF NOT EXISTS idx_kecocokan_event ON aduan_kecocokan (event_id);
-- Paling banyak satu bukti per aduan (di SQLite dijaga oleh aplikasi).
CREATE UNIQUE INDEX IF NOT EXISTS uq_satu_bukti_per_aduan
    ON aduan_kecocokan (aduan_id) WHERE keputusan = 'dikonfirmasi';

CREATE TABLE IF NOT EXISTS aduan_riwayat (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aduan_id        BIGINT      NOT NULL REFERENCES aduan (id) ON DELETE CASCADE,
    waktu           TIMESTAMPTZ NOT NULL DEFAULT now(),
    dari_status     TEXT,
    ke_status       TEXT        NOT NULL,
    oleh            TEXT        NOT NULL DEFAULT 'sistem',
    catatan         TEXT
);
CREATE INDEX IF NOT EXISTS idx_riwayat_aduan ON aduan_riwayat (aduan_id);

CREATE TABLE IF NOT EXISTS kamera_lokasi (
    kamera          TEXT        PRIMARY KEY,
    lat             DOUBLE PRECISION NOT NULL CHECK (lat BETWEEN -90 AND 90),
    lon             DOUBLE PRECISION NOT NULL CHECK (lon BETWEEN -180 AND 180),
    radius_m        INTEGER     NOT NULL DEFAULT 150 CHECK (radius_m BETWEEN 10 AND 2000),
    alamat          TEXT,
    diubah          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- =====================================================================
-- Tampilan siap pakai untuk tim DB / pelaporan
-- =====================================================================

-- Ukuran per kamera: ketepatan deteksi dari keputusan petugas + cakupan.
CREATE OR REPLACE VIEW v_ukuran_kamera AS
SELECT c.camera,
       COUNT(e.id)                                                    AS kejadian,
       COUNT(e.id) FILTER (WHERE e.verified AND e.verdict = 'benar') AS benar,
       COUNT(e.id) FILTER (WHERE e.verified AND e.verdict = 'bukan') AS bukan,
       COUNT(e.id) FILTER (WHERE NOT e.verified)                      AS belum_diputus,
       ROUND(COUNT(e.id) FILTER (WHERE e.verdict = 'benar')::numeric
             / NULLIF(COUNT(e.id) FILTER (WHERE e.verified), 0), 3)   AS ketepatan,
       COUNT(e.id) FILTER (WHERE e.verified)                          AS n_keputusan
  FROM (SELECT DISTINCT camera FROM cycles) c
  LEFT JOIN events e ON e.camera = c.camera
 GROUP BY c.camera;

-- Aduan beserta bukti yang dikonfirmasi (bila ada).
CREATE OR REPLACE VIEW v_aduan_bukti AS
SELECT a.id AS aduan_id, a.sumber, a.ref_sumber, a.kategori, a.lokasi_teks,
       a.waktu_kejadian, a.status, a.cakupan ->> 'keterangan' AS keterangan,
       k.event_id, e.camera, e.kind, e.detected_at, k.skor, k.diputus_pada
  FROM aduan a
  LEFT JOIN aduan_kecocokan k ON k.aduan_id = a.id AND k.keputusan = 'dikonfirmasi'
  LEFT JOIN events e          ON e.id = k.event_id;

-- =====================================================================
-- LC-012: penghitungan lalu lintas Live (butir 1-2 Surat Dishub 1316/KI.03.01)
-- Dialek: PostgreSQL 14+. HANYA ADITIF: tidak mengubah tabel yang sudah ada.
-- Aman dijalankan berulang (IF NOT EXISTS / OR REPLACE).
-- Dijalankan sebagai lalin_app (pemilik skema), supaya lalin_baca otomatis
-- mendapat SELECT lewat ALTER DEFAULT PRIVILEGES di docker/pg-init/01-peran.sh.
--
-- Yang disimpan adalah data MENTAH per kendaraan + versi aturan kelas:
-- label detektor, status (CLASSIFIED/AMBIGUOUS/UNKNOWN), kandidat, jumlah
-- pengamatan & skor. Isi kelas saat ini PROVISIONAL (PKJI 2023, menunggu
-- konfirmasi Dishub); bila taksonomi berubah, hitungan dapat dihitung ulang
-- dari kolom mentah tanpa kehilangan data.
--
-- DATA PRIBADI: tidak ada gambar, pelat nomor, atau identitas. track_id hanya
-- nomor pelacak dalam satu sesi (UU No. 27/2022).
-- =====================================================================

SET search_path TO lalin;

-- Cakupan: kapan sebuah kamera BENAR-BENAR dihitung. Live menghitung satu
-- kamera sekaligus dan hanya selama ada yang menonton, sehingga "tidak ada
-- baris lintas" harus dibedakan dari "tidak sedang dihitung".
CREATE TABLE IF NOT EXISTS sesi_hitung (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesi_id          TEXT        NOT NULL UNIQUE,     -- penanda sesi Live (ms epoch saat mulai)
    camera           TEXT        NOT NULL,
    mulai_pada       TIMESTAMPTZ NOT NULL,
    akhir_pada       TIMESTAMPTZ,                     -- frame terakhir yang diolah
    n_frame          INTEGER     NOT NULL DEFAULT 0,  -- frame diolah (interval 0,6 dtk)
    detik_terhitung  REAL        NOT NULL DEFAULT 0,  -- detik dengan garis aktif (posisi kamera cocok)
    n_lintas         INTEGER     NOT NULL DEFAULT 0,
    garis            JSONB,                           -- garis hitung per tampilan saat sesi mulai
    versi_aturan     TEXT,                            -- configs/klasifikasi.yml
    model            TEXT,
    catatan          TEXT                             -- mis. alasan berhenti / galat
);
CREATE INDEX IF NOT EXISTS idx_sesi_hitung_camera ON sesi_hitung (camera, mulai_pada);

-- Satu baris per kendaraan yang melintasi garis hitung.
CREATE TABLE IF NOT EXISTS lintas_kendaraan (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesi_id          TEXT        NOT NULL REFERENCES sesi_hitung (sesi_id),
    seq              INTEGER     NOT NULL,            -- urutan dalam sesi
    camera           TEXT        NOT NULL,
    waktu            TIMESTAMPTZ NOT NULL,            -- jam server saat frame lintas diolah (tertinggal latensi HLS beberapa detik)
    pts              DOUBLE PRECISION,                -- PTS MPEG-TS (sinkron dengan video di dasbor)
    track_id         TEXT,
    tampilan         INTEGER,                         -- indeks tampilan PTZ (0 = pertama)
    ruas             INTEGER,                         -- indeks garis dalam tampilan (0 = pertama)
    arah             SMALLINT    CHECK (arah IN (0, 1)),
    label_detektor   TEXT,                            -- L1: label COCO mentah (car, bus, truck, ...)
    kelas_tampil     TEXT        NOT NULL,            -- kunci tampil: 7 kelas, atau bus/truk/tidak_dikenal
    status           TEXT        NOT NULL CHECK (status IN ('CLASSIFIED', 'AMBIGUOUS', 'UNKNOWN', 'REJECTED')),
    final_class      TEXT,                            -- L3: kelas Dishub; NULL bila AMBIGUOUS/UNKNOWN
    kandidat         JSONB,                           -- kelas yang mungkin (AMBIGUOUS)
    n_lihat          INTEGER,                         -- jumlah pengamatan track
    n_yakin          INTEGER,                         -- pengamatan di atas ambang kelas
    skor_maks        REAL,
    skor_rata        REAL,
    malam            BOOLEAN,
    bbox             JSONB,                           -- [x, y, w, h] pada 640x360 saat melintas
    versi_aturan     TEXT        NOT NULL,
    dicatat_pada     TIMESTAMPTZ NOT NULL DEFAULT now(),
    alasan_status    TEXT,                            -- LC-015: yakin_rendah / orang_di_badan_jalan / label_detektor_ambigu
    jenis_garis      TEXT,                            -- LC-015: kendaraan / pejalan
    UNIQUE (sesi_id, seq)
);
-- LC-015 (27-09-2026): kolom tambahan untuk tabel yang sudah dibuat LC-012.
ALTER TABLE lintas_kendaraan ADD COLUMN IF NOT EXISTS alasan_status TEXT;
ALTER TABLE lintas_kendaraan ADD COLUMN IF NOT EXISTS jenis_garis   TEXT;
CREATE INDEX IF NOT EXISTS idx_lintas_camera_waktu ON lintas_kendaraan (camera, waktu);

-- Rekap 15 menit per kamera per kelas tampil (untuk tim DB / pelaporan).
-- Kelas KS/BB/TB belum dapat dipisahkan model saat ini; bus & truk tercatat
-- sebagai AMBIGUOUS dengan kandidatnya.
CREATE OR REPLACE VIEW v_hitung_15mnt AS
SELECT camera,
       date_bin('15 minutes', waktu, TIMESTAMPTZ '2000-01-01 00:00+07') AS mulai_15mnt,
       kelas_tampil, status, versi_aturan,
       COUNT(*) AS jumlah
  FROM lintas_kendaraan
 GROUP BY 1, 2, 3, 4, 5;
