-- =====================================================================
-- LC-012: penghitungan lalu lintas Live (butir 1-2 Surat Dishub 1316/KI.03.01)
-- Dialek: PostgreSQL 14+. HANYA ADITIF: tidak mengubah tabel yang sudah ada.
-- Aman dijalankan berulang (IF NOT EXISTS / OR REPLACE).
-- Dijalankan sebagai lalin_app (pemilik skema), supaya lalin_baca otomatis
-- mendapat SELECT lewat ALTER DEFAULT PRIVILEGES di docker/pg-init/01-peran.sh.
--
-- Yang disimpan adalah data MENTAH per kendaraan + versi aturan kelas:
-- label detektor, status (CLASSIFIED/AMBIGUOUS/UNKNOWN), kandidat, jumlah
-- pengamatan & skor. Isi kelas saat ini PROVISIONAL (PKJI 2023, menunggu
-- konfirmasi Dishub); bila taksonomi berubah, hitungan dapat dihitung ulang
-- dari kolom mentah tanpa kehilangan data.
--
-- DATA PRIBADI: tidak ada gambar, pelat nomor, atau identitas. track_id hanya
-- nomor pelacak dalam satu sesi (UU No. 27/2022).
-- =====================================================================

SET search_path TO lalin;

-- Cakupan: kapan sebuah kamera BENAR-BENAR dihitung. Live menghitung satu
-- kamera sekaligus dan hanya selama ada yang menonton, sehingga "tidak ada
-- baris lintas" harus dibedakan dari "tidak sedang dihitung".
CREATE TABLE IF NOT EXISTS sesi_hitung (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesi_id          TEXT        NOT NULL UNIQUE,     -- penanda sesi Live (ms epoch saat mulai)
    camera           TEXT        NOT NULL,
    mulai_pada       TIMESTAMPTZ NOT NULL,
    akhir_pada       TIMESTAMPTZ,                     -- frame terakhir yang diolah
    n_frame          INTEGER     NOT NULL DEFAULT 0,  -- frame diolah (interval 0,6 dtk)
    detik_terhitung  REAL        NOT NULL DEFAULT 0,  -- detik dengan garis aktif (posisi kamera cocok)
    n_lintas         INTEGER     NOT NULL DEFAULT 0,
    garis            JSONB,                           -- garis hitung per tampilan saat sesi mulai
    versi_aturan     TEXT,                            -- configs/klasifikasi.yml
    model            TEXT,
    catatan          TEXT                             -- mis. alasan berhenti / galat
);
CREATE INDEX IF NOT EXISTS idx_sesi_hitung_camera ON sesi_hitung (camera, mulai_pada);

-- Satu baris per kendaraan yang melintasi garis hitung.
CREATE TABLE IF NOT EXISTS lintas_kendaraan (
    id               BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesi_id          TEXT        NOT NULL REFERENCES sesi_hitung (sesi_id),
    seq              INTEGER     NOT NULL,            -- urutan dalam sesi
    camera           TEXT        NOT NULL,
    waktu            TIMESTAMPTZ NOT NULL,            -- jam server saat frame lintas diolah (tertinggal latensi HLS beberapa detik)
    pts              DOUBLE PRECISION,                -- PTS MPEG-TS (sinkron dengan video di dasbor)
    track_id         TEXT,
    tampilan         INTEGER,                         -- indeks tampilan PTZ (0 = pertama)
    ruas             INTEGER,                         -- indeks garis dalam tampilan (0 = pertama)
    arah             SMALLINT    CHECK (arah IN (0, 1)),
    label_detektor   TEXT,                            -- L1: label COCO mentah (car, bus, truck, ...)
    kelas_tampil     TEXT        NOT NULL,            -- kunci tampil: 7 kelas, atau bus/truk/tidak_dikenal
    status           TEXT        NOT NULL CHECK (status IN ('CLASSIFIED', 'AMBIGUOUS', 'UNKNOWN', 'REJECTED')),
    final_class      TEXT,                            -- L3: kelas Dishub; NULL bila AMBIGUOUS/UNKNOWN
    kandidat         JSONB,                           -- kelas yang mungkin (AMBIGUOUS)
    n_lihat          INTEGER,                         -- jumlah pengamatan track
    n_yakin          INTEGER,                         -- pengamatan di atas ambang kelas
    skor_maks        REAL,
    skor_rata        REAL,
    malam            BOOLEAN,
    bbox             JSONB,                           -- [x, y, w, h] pada 640x360 saat melintas
    jejak            JSONB,                           -- PTS/bbox/skor/label per pengamatan track; tanpa gambar/identitas
    versi_aturan     TEXT        NOT NULL,
    dicatat_pada     TIMESTAMPTZ NOT NULL DEFAULT now(),
    alasan_status    TEXT,                            -- LC-015: yakin_rendah / orang_di_badan_jalan / label_detektor_ambigu
    jenis_garis      TEXT,                            -- LC-015: kendaraan / pejalan
    UNIQUE (sesi_id, seq)
);
-- LC-015 (27-09-2026): kolom tambahan untuk tabel yang sudah dibuat LC-012.
ALTER TABLE lintas_kendaraan ADD COLUMN IF NOT EXISTS alasan_status TEXT;
ALTER TABLE lintas_kendaraan ADD COLUMN IF NOT EXISTS jenis_garis   TEXT;
ALTER TABLE lintas_kendaraan ADD COLUMN IF NOT EXISTS jejak         JSONB;
CREATE INDEX IF NOT EXISTS idx_lintas_camera_waktu ON lintas_kendaraan (camera, waktu);

-- Rekap 15 menit per kamera per kelas tampil (untuk tim DB / pelaporan).
-- Kelas KS/BB/TB belum dapat dipisahkan model saat ini; bus & truk tercatat
-- sebagai AMBIGUOUS dengan kandidatnya.
CREATE OR REPLACE VIEW v_hitung_15mnt AS
SELECT camera,
       date_bin('15 minutes', waktu, TIMESTAMPTZ '2000-01-01 00:00+07') AS mulai_15mnt,
       kelas_tampil, status, versi_aturan,
       COUNT(*) AS jumlah
  FROM lintas_kendaraan
 GROUP BY 1, 2, 3, 4, 5;
